spring.application.name=PiggyFinance


spring.datasource.url=jdbc:mysql://localhost:3306/finance?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=postgres
spring.datasource.password=

# Configurações do JPA / Hibernate
# update: Cria as tabelas se não existirem ou atualiza se houver mudanças
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect